# Generated by Django 2.0.5 on 2018-05-25 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField()),
                ('humidity', models.IntegerField()),
                ('wind_strenght', models.IntegerField()),
                ('wind_direction', models.CharField(max_length=4)),
                ('date_of_record', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
