# Generated by Django 2.0.5 on 2018-05-25 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kg', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatherdata',
            name='wind_direction',
            field=models.CharField(max_length=5),
        ),
    ]
