# Generated by Django 2.0.5 on 2018-05-25 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kg', '0002_auto_20180525_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatherdata',
            name='wind_direction',
            field=models.CharField(max_length=5, verbose_name=('NORTH', 'SOUTH', 'EAST', 'WEST')),
        ),
    ]
